name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Klonowanie repozytorium
      uses: actions/checkout@v4

    - name: Konfiguracja Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Konfiguracja środowiska Java (Gradle)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalacja zależności projektu
      run: npm ci # Użyj npm ci zamiast npm install dla środowisk CI (szybciej i stabilniej)

    - name: Budowanie aplikacji webowej
      run: npm run build

    - name: Synchronizacja z platformą Android (Capacitor)
      run: npx cap sync android

    - name: Nadanie uprawnień i budowanie APK (Debug)
      working-directory: ./android
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Przesłanie pliku APK jako artefaktu
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
